# ROI de uma Imagem:


Um conceito importante em processamento de imagens é a **Região de Interesse**. Entende-se como Região de Interesse (ROI - "Region Of Interest" ou AOI - "Area Of Interest") a região obtida de maneira automática ou a partir da interação de um usuário onde o processamento estará totalmente concentrado. 

### Objetivos:

1. Obter um ROI de uma imagem a partir da área selecionada pelo mouse



In [1]:
# Bibliotecas
import cv2
import numpy as np

# Imagem teste
image = cv2.imread('lena.png')
image_to_show = np.copy(image)

# Estados iniciais do mouse
cropping = False
x_init, y_init, top_left_pt, bottom_right_pt = 0, 0, 0, 0


def roi(event, x, y, flags, param):
    global image_to_show, x_init, y_init, top_left_pt, bottom_right_pt, cropping

    if event == cv2.EVENT_LBUTTONDOWN:
        cropping = True
        x_init, y_init = x, y
        image_to_show = np.copy(image)
        print(f'Ponto inicial em X {x_init}')
        print(f'Ponto inicial em Y {y_init}')

    elif event == cv2.EVENT_MOUSEMOVE:
        if cropping == True:
            image_to_show = np.copy(image)
            cv2.rectangle(image_to_show, (x_init, y_init),
                          (x, y), (0, 255, 0), 1)

    elif event == cv2.EVENT_LBUTTONUP:
        cropping = False
        top_left_pt, bottom_right_pt = x, y
        print(f'Ponto superior {top_left_pt}')
        print(f'Ponto inferior {bottom_right_pt}')


cv2.namedWindow('image')
cv2.setMouseCallback('image', roi)

while True:

    cv2.imshow('image', image_to_show)
    k = cv2.waitKey(1)

    if k == ord('c'):
        if y_init > bottom_right_pt:
            y_init, bottom_right_pt = bottom_right_pt, y_init
        if x_init > top_left_pt:
            x_init, top_left_pt = top_left_pt, x_init

        if bottom_right_pt - y_init > 1 and top_left_pt - x_init > 0:
            image = image[y_init:bottom_right_pt, x_init:top_left_pt]
            print(image)
            image_to_show = np.copy(image)

    if k == ord('s'):
        cv2.imwrite('teste.jpg', image_to_show)

    if cv2.waitKey(1) == ord('q'):
        break

cv2.destroyAllWindows()


Ponto inicial em X 130
Ponto inicial em Y 153
Ponto superior 390
Ponto inferior 407
Ponto inicial em X 388
Ponto inicial em Y 389
Ponto superior 388
Ponto inferior 389
Ponto inicial em X 380
Ponto inicial em Y 410
Ponto superior 131
Ponto inferior 160
[[[122 161 232]
  [123 167 232]
  [ 99 146 235]
  ...
  [184 193 225]
  [188 198 225]
  [190 202 229]]

 [[109 151 240]
  [ 95 152 240]
  [ 86 111 226]
  ...
  [184 194 228]
  [188 198 227]
  [192 203 226]]

 [[ 92 138 233]
  [ 98 107 227]
  [ 89 102 217]
  ...
  [186 197 223]
  [187 197 223]
  [191 201 226]]

 ...

 [[ 82  39  92]
  [111  57 108]
  [101  45 107]
  ...
  [116 130 215]
  [118 124 205]
  [106 108 197]]

 [[ 86  34  90]
  [100  48  98]
  [100  44 105]
  ...
  [130 133 214]
  [115 126 205]
  [118 110 193]]

 [[ 90  36  91]
  [ 82  37  93]
  [108  54 110]
  ...
  [128 133 215]
  [117 125 206]
  [101 110 192]]]
Ponto inicial em X 89
Ponto inicial em Y 0
Ponto superior 89
Ponto inferior 0
